apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-mecanica-config
data: # Dados não sensíveis
  DatabaseConnection__Host: "__DB_HOST__"
  DatabaseConnection__Port: "5432"
  DatabaseConnection__DatabaseName: "__DB_NAME__"
  DatabaseConnection__User: "__DB_MASTER_USERNAME__"
  
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  
  Jwt__Issuer: "OficinaMecanicaApi"
  Jwt__Audience: "AuthorizedServices"
  
  ApiCredentials__ClientId: "admin"